[project]
name = "runnables"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Chinmay saini", email = "134822774+chinmay-yy@users.noreply.github.com" }
]
requires-python = ">=3.13"
dependencies = []

[project.scripts]
runnables = "runnables:main"

[build-system]
requires = ["uv_build>=0.12.1,<0.13.0"]
build-backend = "uv_build"
